import OpenAI from 'openai';
import { Resend } from 'resend';

// NOTE: You must add RESEND_API_KEY to your .env file
const resend = new Resend(process.env.RESEND_API_KEY);
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    const employee = req.body;
    
    // Extract row data
    const empName = employee['Employee Name'] || 'New Hire';
    const office = employee['Office Location'] || 'Central London';
    const prefs = employee['Preferences'] || '1-Bed Private Flat';
    const salary = Number(employee['Salary']) || 50000;
    const empEmail = employee['Employee Email'];
    const watcherEmail = employee['Watcher Email'];

    if (!empEmail) return res.status(400).json({ error: 'Missing employee email' });

    // 1. Calculate Monthly Budget Cap (Net Pay * 40%)
    const tax = salary > 12570 ? (salary - 12570) * 0.28 : 0;
    const netMonthly = (salary - tax) / 12;
    const numericBudget = Math.round(netMonthly * 0.40);

    // 2. Generate 5 Top Hubs via Clyde
    const prompt = `
    You are Clyde, an Enterprise AI agent. Find the Top 5 best London neighborhoods for an employee commuting to '${office}'.
    Budget: £${numericBudget}/month. Type: '${prefs}'. 
    Return ONLY JSON with a 'hubs' array containing: Neighborhood, Commute_Duration, Rent_Range, AI_Verdict.
    `;

    const aiRes = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [{ role: 'system', content: prompt }],
      response_format: { type: "json_object" }
    });

    const parsed = JSON.parse(aiRes.choices[0].message.content);
    const hubs = parsed.hubs || [];

    // 3. Construct HTML Email
    let htmlContent = `
      <div style="font-family: sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #eaeaea; border-radius: 10px;">
        <h2 style="color: #059669;">Welcome to London, ${empName}!</h2>
        <p>Your HR team has used <strong>KeelEngine Enterprise</strong> to curate the perfect neighborhoods for your commute to ${office}.</p>
        <p>Based on your assigned salary tier and property preference (${prefs}), here are your top 5 viable matches:</p>
        <hr style="border: none; border-top: 1px solid #eaeaea; margin: 20px 0;" />
    `;

    hubs.forEach((hub, idx) => {
      const searchUrl = `https://www.zoopla.co.uk/to-rent/property/${encodeURIComponent(hub.Neighborhood.replace(/\s+/g, '-').toLowerCase())}/`;
      htmlContent += `
        <div style="margin-bottom: 20px; padding: 15px; background-color: #f9fafb; border-radius: 8px;">
          <h3 style="margin: 0 0 10px 0; color: #111827;">${idx + 1}. ${hub.Neighborhood}</h3>
          <p style="margin: 5px 0; font-size: 14px;"><strong>Commute:</strong> ${hub.Commute_Duration} Mins</p>
          <p style="margin: 5px 0; font-size: 14px;"><strong>Estimated Rent:</strong> ${hub.Rent_Range}</p>
          <p style="margin: 10px 0; font-size: 14px; color: #4b5563;"><em>"${hub.AI_Verdict}"</em></p>
          <a href="${searchUrl}" style="display: inline-block; background-color: #059669; color: white; text-decoration: none; padding: 8px 12px; border-radius: 5px; font-size: 12px; font-weight: bold;">View Live Listings on Zoopla</a>
        </div>
      `;
    });

    htmlContent += `
        <p style="font-size: 12px; color: #9ca3af; margin-top: 30px;">This automated briefing was generated by KeelEngine for your employer. CC: ${watcherEmail}</p>
      </div>
    `;

    // 4. Dispatch Email via Resend
    await resend.emails.send({
      from: 'KeelEngine Enterprise <hello@yourdomain.com>', // Update to your verified Resend domain
      to: [empEmail],
      cc: watcherEmail ? [watcherEmail] : [],
      subject: `Your London Relocation Matches - KeelEngine`,
      html: htmlContent
    });

    return res.status(200).json({ success: true });
  } catch (error) {
    console.error("Batch Error:", error);
    return res.status(500).json({ error: "Failed to process row." });
  }
}